app:
  name: kdbe
  version: 1.0.0


## RDB Property (AWS RDS), MongoDB, Redis
spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://toy-db.c0yxo9fizkk3.ap-northeast-2.rds.amazonaws.com:3306/kdproject?useUnicode=true&characterEncoding=UTF-8
    username: admin
    password: rlatpdud13795
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MariaDBDialect
    show-sql: true
    format-sql: true
  redis:
    host: 54.180.24.185
    port: 6379


  data:
    mongodb:
      host: 54.180.24.185
      port: 27017
      database: my-service
  sql:
    init:
      encoding: UTF-8

logging:
  level:
    com.example.kdbe: debug

auth:
  secretKey: kdbe
  AUTH_EXPIRY: 1200000 #20min
  REFRESH_EXPIRY: 8000000 #6hours